# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'secretconnection'
    subscriptionId: '40082912-9b85-4009-a183-1f5cf2c69fdf'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-decker'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'secretconnection'
    appType: 'webAppLinux'
    WebAppName: 'my-app-decker'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'